### ISSUE TITLE
1.6.0 update bugs

### ISSUE THREAD

**Issue by test2a** [stom79/TubeLab#65] opened 2020-11-10 12:33 UTC
### Issue

i am very very happy and excited about the update. it has improved so much functionality on the app but there are some bugs i have come across and i would write them once on this issue and open subsequent issues later on.
let me just tell you you have done a brilliant job already and my good wishes to you.

so,
* [feature] double click video middle to go fullscreen
* [bug] selecting low resolution fixes to 0p making video impossible. i think a minimum 240p should be set for this setting until proper resolutions can be used
* [bug] screen lock is not working. videos did not play when screen was off nor when app was moved to recent.
* [bug[ settings for authenticated mode is in account. it should be global for all accounts like unauthenticated mode.
* [bug] "enter" button in login page does not switch to next box. you have to enter say instance information. click back, then click on username. write username. back. then again enter password. then again back and then login. pressing enter button should go to next box automatically.
* [bug] suffix"/" is causing client id error just like http:// in previous version
* [bug] notifications should have light/dark tint depending on viewed/unviewed notification.

* [feature] writing a comment should be in fullscreen mode only as that way we can type in a lot more than the box size and check for mistakes, do corrections.
* [discussion] mode for videos is unclear. what does normal, webview, magnet and torrent mean?
* [bug] fullscreen mode on causes 100% app crash when clicking on video
*  [feature] app crash should give error code for debugging. right now the app simply crashes. 
* [feature] clear history button in history tab
* [bug] enable history feature not in sync with web. we should either adjust web history also when the history is disabled in app or the app should say that this disable history is for current app only. 
* [feature] notification of video playing onscreen/background/lockscreen for pause/play/forward
* [bug] editing a video having long description shows only truncated description on phone edit. saving the edit causes the rest of description to delete.
* [feature] display warning on activating "display sensitive content" setting
* [bug] theme setting has wrong label. it should be "change the app theme"
* [bug] "minimize video size" still has issues. i should write detailed info on that.
* [bug] when video has finished, pressing play button "should" go to start. it is currently doing nothing. or as in case of many apps, once video finishes, it turns to a "replay video" button.
* [bug] reply comments still have username of person. that should serves no purpose
* [bug] lanscape mode has multiple issues. i will write a dedicated issue for this
* [feature] black mode in theme
* [feature] allow accent color change. having only orange in text and interface would not be fun for some.
* [feature] allow updating own profile picture/channel photo
* [feature] "mark all as read" notification button 
* [feature] notification count
* [bug] dark mode. sepia search page has top part white when it should be dark
* [bug] many video description is still truncated only. for example this link https://devtube.dev-wiki.de/videos/watch/183d2833-6d5d-42eb-8ab3-351876aca731
* [bug] just rewriting an old bug, i think the thumbnails/images pulled are of low quality. this just makes the app look old

i think that should be enough for one day ;-)

- [x ] TubeLab
- [ ] TubeAcad

Version of TubeLab:1.6.0

Android version:

**Comment by stom79** [comment] 2020-11-10 17:48
Thanks I will look into that. That's a bulk feedback :smile:

**Comment by test2a** [comment] 2020-11-10 18:16
haha. yeah. you had fixed the popup window bug last time but i think it is still wonky. how about we only go to popup player if the user clicks on the popup player button like newpipe? i had it on for like 10 minutes and i felt really stupid trying to wiggle the small video window while i wanted to get back to other stuff.

**Comment by test2a** [comment] 2020-11-10 18:45
@stom79 i will put this here. video display in landscape mode
![Screenshot_20201110-172748](https://user-images.githubusercontent.com/39449563/98717295-dfc03a80-23b2-11eb-96e9-803f4c20da81.png)

**Comment by stom79** [comment] 2020-11-15 09:00
This long issue is not easy to fix. We should split most important bug fixes in different tickets.

**Comment by stom79** [comment] 2020-11-15 09:02
For instance, this one: 
>[bug] selecting low resolution fixes to 0p making video impossible. i think a minimum 240p should be set for this setting until proper resolutions can be used

0dp should already be discarded, so talking about that with multi-issues in a same thread is impossible :(

**Comment by stom79** [comment] 2020-11-15 09:03
> [bug] suffix"/" is causing client id error just like http:// in previous version

I can't reproduce it.

**Comment by stom79** [comment] 2020-11-15 09:05
> [bug] fullscreen mode on causes 100% app crash when clicking on video

Same, I can't reproduce it.

**Comment by stom79** [comment] 2020-11-15 09:07
> [bug] reply comments still have username of person. that should serves no purpose

If you reply to someone, the mention will notify this account. For instance a Mastodon account will receive it. That's how the site works too.

**Comment by stom79** [comment] 2020-11-15 09:08
> [bug] lanscape mode has multiple issues. i will write a dedicated issue for this

I didn't use the app in landscape, `1.7.0` will fix some of them already.

**Comment by stom79** [comment] 2020-11-16 18:30
I am reworking the whole video settings. A general settings button will be displayed in the video (in controller), that will open options like resolution, automatically play next video, subtitles, speed playback, etc..
I fixed all issues (crashes with auto fullscreen). Before going further, my goal is to improve the player with quick access to main important features.

**Comment by stom79** [comment] 2020-11-17 19:45
Do you have knowledge to compile the code from sources? If not, do you want me to share with you apk for your tests before releases?

**Comment by test2a** [comment] 2020-11-18 06:25
@stom79 unfortunately no. my technical skills are restricted to html/css only. *sighs*. i can do documentation and testing though.  an apk would be good

**Comment by stom79** [comment] 2020-11-18 15:12
Could you try this apk? https://framadrive.org/s/FrWan56nAegNG58

**Comment by test2a** [comment] 2020-11-18 15:23
Sorry unable to install. Says app not installed.

**Comment by stom79** [comment] 2020-11-18 15:24
You have to remove tubelab first

**Comment by test2a** [comment] 2020-11-18 16:21
@stom79 okay. that worked and i am very happy with more improvements. one thing. the video player is now better with the video player cog but two issues
* the dark overlay that shows up on clicking the cog does not go away on its own. the screen needs to be clicked to hide the video overlay
* [important] any radiobutton in the cog menu takes multiple attempts to select. the screen actually closes if i select any option and it seems it closes faster than the option has chance to register
* [bug] the video player switches to next video when when the settings option is disabled to autoplay next video. even if the play video automatically is off, the video still switches to next one.

**Comment by test2a** [comment] 2020-11-18 16:25
@stom79 liking own videos, add to playlist and even the edit video crashes the app

**Comment by stom79** [comment] 2020-11-18 16:26
> the dark overlay that shows up on clicking the cog does not go away on its own. the screen needs to be clicked to hide the video overlay

You mean it should be timed out for auto-closing?

**Comment by stom79** [comment] 2020-11-18 16:26
>@stom79 liking own videos, add to playlist and even the edit video crashes the app

Is it always the instance having issues?

**Comment by test2a** [comment] 2020-11-18 16:30
@stom79 yes. liking own videos has crashing 100% since last two updates. edit video i just saw on the debug version. dunno

**Comment by stom79** [comment] 2020-11-18 16:30
Wow ok. I didn't test for my videos.

**Comment by stom79** [comment] 2020-11-18 18:19
OK. I fixed some of the issues that you mentioned. Here is the new apk https://framadrive.org/s/5ae5LinGaQbnXEi
No need to uninstall this time if you are still running the other apk.

**Comment by test2a** [comment] 2020-11-18 18:29
![Screenshot_20201118-235539](https://user-images.githubusercontent.com/39449563/99571785-c8f49600-29f9-11eb-9422-cccf6c9200ac.png)
@stom79 ok. found out this hapens if i click on the radio button itself. clicking on text now does the desired action but radiobutton is problematic

**Comment by test2a** [comment] 2020-11-18 18:31
> > the dark overlay that shows up on clicking the cog does not go away on its own. the screen needs to be clicked to hide the video overlay
> 
> You mean it should be timed out for auto-closing?

@stom79 no. what i mean is if i click on the cog, say i select a resolution, the window closes but the overlay remains. overlay should also close. right now it needs a tap to close.

**Comment by test2a** [comment] 2020-11-18 18:32
@stom79 the edit video crash is now happening always.

**Comment by stom79** [comment] 2020-11-18 18:32
>@stom79 no. what i mean is if i click on the cog, say i select a resolution, the window closes but the overlay remains. overlay should also close. right now it needs a tap to close.

OK got it.

**Comment by stom79** [comment] 2020-11-18 18:47
OK I will fix edit crashes. For next release, I will start to fix only crashes and unwanted behaviors to release ASAP.

**Comment by test2a** [comment] 2020-11-18 18:51
@stom79 there is no need to set a high bar for yourself. let the bugs be for a day or two. when building a great app, we have to look at say a year ahead. unless there is some catastrophic bug, you should not work yourself out. just my two cents. you are doing a great job, just dont overdo it ;-)

**Comment by stom79** [comment] 2020-11-19 17:17
A new apk fixing some of your suggestions/bug reports (see: https://github.com/stom79/TubeLab/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc)

I also moved the auto-play next video feature in player

Download: https://framadrive.org/s/Gi76FaRWXHwdynf

**Comment by test2a** [comment] 2020-11-19 18:01
@stom79 good work. many things have improved. the thumbnail one was really hurting my eyes though. now its reaaally better.

can we have "~/my-account/subscriptions" page style list in the subscriptions tab because if i wanted to unsubscribe from someone, i just have to find their video and unsubscribe from there. not easy managing your subscriptions list.

other than the open issues and probably this one, the update looks nice.

oh, earlier saw this but it is something you should look at. 

the profile and upload icons only show up if i turn the app in landscape mode and open a video. once out of video fullscreen, these icons show up. they aren't bad so if this is intentional, the profile icon should be there at least. 

![Screenshot_20201119-232617](https://user-images.githubusercontent.com/39449563/99704843-f35c5700-2abe-11eb-8df3-fac1d75cd428.png)
![Screenshot_20201119-232623](https://user-images.githubusercontent.com/39449563/99704850-f6574780-2abe-11eb-86e7-9fac8a577c59.png)

**Comment by test2a** [comment] 2020-11-19 18:04
also this comment on url intent
https://github.com/stom79/TubeLab/issues/91#issuecomment-729682247

**Comment by stom79** [comment] 2020-11-19 18:09
These icons are displayed if there are enough space (automatically calculated). That's why landscape mode displays more of them. Their order plays a role.

**Comment by stom79** [comment] 2020-11-19 18:11
But I confirm the issue. They should have been redrown when changing the orientation.

**Comment by test2a** [comment] 2020-11-19 18:33
@stom79 you should implement your yesterdays suggestion of a timer to hide the overlay in the video player

**Comment by stom79** [comment] 2020-11-19 18:40
>@stom79 you should implement your yesterdays suggestion of a timer to hide the overlay in the video player

Why? I found your idea make more sense as the controller reminds open until no action is done. YouTube player acts like this.

**Comment by stom79** [comment] 2020-11-19 18:41
>the fullscreen player is not accepting accelerometer orientation i think. it is stuck to one side even if i have autorotate on and the video is playing upside down

Hum, OK I will check that.

**Comment by test2a** [comment] 2020-11-20 17:20
i used the app for the entire day today and only thing i missed were volume and brightness controls in the player.

**Comment by stom79** [comment] 2020-11-21 10:19
> yes. the app does seem to share original instance URL instead of upstream default of local video and that is why i think many remote videos are not working. if i have subscribed to a remote instance, the web version of that video becomes my local instance. say https://videos.lukesmith.xyz/videos/watch/4ab0c2b6-0f1c-4904-beca-a02c53e8bc1c after subscription becomes
https://tube.ouahpiti.info/videos/watch/4ab0c2b6-0f1c-4904-beca-a02c53e8bc1c which is playable on the desktop but because the app tries to resolve remote URL, it fails to load videos. i have now observed this particular video in my notifications where the link is second one and it works but the app somehow wants to resolve to first link and then it fails. it should try the second link and check if it works. if not, then try the first one and then again if not, throw error specifying this issue

The app uses the channel host when sharing a video link. I might don't get it? So when sharing, this link is used  https://videos.lukesmith.xyz/videos/watch/4ab0c2b6-0f1c-4904-beca-a02c53e8bc1c  and not the other one.

**Comment by test2a** [comment] 2020-11-21 10:56
yes. check this pr https://github.com/Chocobozzz/PeerTube/pull/3201

the app is doing what this pr does with a checkbox. the default is to not do it. this just ads an option.

**Comment by stom79** [comment] 2020-11-21 11:04
But that can be related to the fact videos are not working. I didn't get that point. Because, if it was not the original instance, you could not play it like you said with https://tube.ouahpiti.info/videos/watch/4ab0c2b6-0f1c-4904-beca-a02c53e8bc1c

**Comment by test2a** [comment] 2020-11-21 11:20
if you are logged in, it works. i can give you the credentials, its just a burner login. 
![Screenshot_20201121_164904](https://user-images.githubusercontent.com/39449563/99875960-91643480-2c19-11eb-81f5-1ff0265d2207.png)

**Comment by test2a** [comment] 2020-11-21 12:49
Test (at) spam4 . Me
Test @ 123

Check the web version, the notification about Luke Smith points to local link which plays. On the phone it does not. Same for subscriptions in the phone. In the web, those remote videos work but not on the phone.

**Comment by stom79** [comment] 2020-11-21 18:00
Wow. I understood. When you talked about sharing I though the feature to share which returns the correct link (ok the remote one but which works all the time).

When searching a URL, the app checked locally it exists and didn't play it when it was not federated. I fixed that. There are also some other fixes and improvement (like changing channel avatar, upload issue, etc.)

You can test this version: 
https://framadrive.org/s/JigsiYyxkMk3x9X

**Comment by test2a** [comment] 2020-11-21 18:08
nice. liking says its not federated which is fine by me right now.  same for comments but there seems to be a bug. main "add a public reply" button says the message but if i click on a comment, another page shows up and a pseudo entry page shows and nothing happens. i am sure you can sort that out.

oh, in the subscriptions if i click on the channel image, this luke one in particular, nothing shows. i am able to now click the notifications though

**Comment by test2a** [comment] 2020-11-21 18:12
now that we are able to resolve and play remote videos, i want to understand why does it say "not federated" because if i follow the screenshot notification and the video, i am able to like and comment just as easily. you can check that on the desktop
https://videos.lukesmith.xyz/videos/watch/4ab0c2b6-0f1c-4904-beca-a02c53e8bc1c;threadId=3728  i think this is the thread. i wrote "yeah" to a comment. this while i was watching this video on https://tube.ouahpiti.info/videos/watch/4ab0c2b6-0f1c-4904-beca-a02c53e8bc1c link as i earlier mentioned

this is now a less of a deal because the videos at least work. you should probably move your attention towards other stuff. this is a win for sure

**Comment by stom79** [comment] 2020-11-21 18:15
Previously, were you able to play this videos when coming from notifications?

**Comment by test2a** [comment] 2020-11-21 18:16
nope. the notifications showed nothing. now the video plays fine but no lliking or commenting in app but able to do that on browser

**Comment by test2a** [comment] 2020-11-21 18:18
also, the uploads now work but i have a suggestion, the "edit" video should open to the now successfully uploaded video because the first time we don't take much data except the name and privacy.

**Comment by stom79** [comment] 2020-11-21 18:25
When clicking the notification saying the video has been uploaded, it opens the edit activity for the video. Is it not enough?

**Comment by stom79** [comment] 2020-11-21 18:26
>nope. the notifications showed nothing. now the video plays fine but no lliking or commenting in app but able to do that on browser

OK. So it's not a federation issue if it only happens when searching or clicking a video from subscriptions timeline.

**Comment by test2a** [comment] 2020-11-21 18:28
> When clicking the notification saying the video has been uploaded, it opens the edit activity for the video. Is it not enough?

it did not open it. that is what i was expecting and thats why i wrote about it :-)

**Comment by test2a** [comment] 2020-11-21 18:31
ok. found a bunch of crashes
![recording_20201121_235217](https://user-images.githubusercontent.com/39449563/99884597-816a4600-2c55-11eb-8e87-34b74759c525.gif)

there are two crashes. one in notifications. then i show another notification that works fine and then a second crash in subscriptions when i try to play a video i know is a remote one

so if you want to check in the app yourself
https://devtube.dev-wiki.de
same username
Test @ 123 as the acces code

**Comment by test2a** [comment] 2020-11-21 18:48
oh. i think i got it. i get a crash on notifications where someone has replied to you meaning ";threadId=7100" as the suffix to video link. that is why the app is crashing. it isnt able to resolve the threadid meaning the specific comment

**Comment by test2a** [comment] 2020-11-21 19:09
this may not be much but i was trying to unfollow a "channel" but the message says "do yiu want to unfollow this account?". it should say " do you want to unfollow this channel?"
second, the second line lists the address of the channel, it should IMO have the display name because that is what people are most familiar with. address be long like the one in screenshot and might confuse users.

![Screenshot_20201122-003520](https://user-images.githubusercontent.com/39449563/99885432-e07e8980-2c5a-11eb-8e1f-4378af70c967.png)

**Comment by stom79** [comment] 2020-11-21 19:12
You're right. Could you open separate issues for such cases. No need to rewrite the description just link to comments on that thread.

**Comment by stom79** [comment] 2020-11-21 19:15
I should remove all this unfollow/follow words with subscribe/unsubscribe. These words inherit from fedilab.

**Comment by test2a** [comment] 2020-11-23 16:38
@stom79 hi. the update to 1.8 is good. the remote videos now dont show federation error message which is nice. instead a weird bug. i am able to see the videos of a remote channel but clicking on the channel image to reach the profile it says no videos to display. 


![Screenshot_20201123-220102](https://user-images.githubusercontent.com/39449563/99988536-b8686500-2dd7-11eb-976d-3cfc6ed61e3e.png)
![Screenshot_20201123-220123](https://user-images.githubusercontent.com/39449563/99988554-ba322880-2dd7-11eb-9255-4ff57e7fb125.png)
![Screenshot_20201123-220110](https://user-images.githubusercontent.com/39449563/99988683-d33ad980-2dd7-11eb-9748-f6ac4234650a.png)

**Comment by test2a** [comment] 2020-11-23 16:48
@stom79 you already fixed the automatic playback to "autoplay next video" in the video player but it is still present. it HAS changed in the settings though so half is fixed. 

it says "autoplay" in the first window and "automatic playback" in the second window.

![Screenshot_20201123-221439](https://user-images.githubusercontent.com/39449563/99990286-a5ef2b00-2dd9-11eb-85a8-907b17bf2db0.png)

**Comment by test2a** [comment] 2020-11-24 08:27
@stom79 app crashes on theme change and sometimes in settings

**Comment by test2a** [comment] 2020-11-25 11:53
@stom79 i just found out how the "screen lock" works. 

play a video. close the screen
video stops
enter fullscreen. close the screen
video stops

now, press back and the popup player plays
close the screen
video plays in background.

is this intentional? i happened to come across this only after trying multiple things. can we have a dedicated button like near like and dislike button like a headphones icon and pressing that the audio only plays and that way the screen can be turned off and it should continue

**Comment by test2a** [comment] 2020-11-27 08:10
New crash.

Paste https://tube.jeena.net/videos/watch/51a189cf-3372-4f97-9ff7-b5982dce4c9e
In search. Video sometimes plays twice, meaning one I can control and another in background. Only way to stop is by force quit app.
Secondly,  once this video is playing liking crashes the app.

But if I subscribe to this channel, then in my subscriptions the video is fine and I can like easily.

**Comment by stom79** [comment] 2020-11-27 18:03
A new release for tests: https://framadrive.org/s/A78Kwg86nXdbZMZ

**Comment by test2a** [comment] 2020-11-27 18:38
@stom79 quick test results
* i love the new comments format. this is what i had in mind and it looks super nice. thanks
* first time login> theme change crashes app but also logs out from instance. have to re login.
* set automatic playback off. then open https://tube.jeena.net/videos/watch/51a189cf-3372-4f97-9ff7-b5982dce4c9e link. i had earlier watched this video til halfway and when i click on this link, for a second the video plays from start, then another player opens from last watched place. if i had autoplay on, then two videos would have run at once. THIS IS A BUG

* same with searching this video link. two audios are heard and only one display.

* "auto play" and "automatic playback" in video player should say "autoplay next video". this has not been fixed

*

**Comment by stom79** [comment] 2020-11-27 18:48
Yes, I will work for fixing theme crashes. Also I will prompt a pop-up before logging out the account with a retry that should fix the token issue after a crash.

**Comment by stom79** [comment] 2020-11-27 18:50
Yes, I didn't fix all bugs but thanks for telling me most important ones to fix.

**Comment by test2a** [comment] 2020-11-27 18:52
@stom79 not an issue. i just found another bug.i have a notification, "your abuse report has been accepted". it should do nothing as it was doing in previous versions until you implement that portion of website but now clicking on a notification plays one of my own videos. dont know why it is happening

**Comment by test2a** [comment] 2020-11-27 18:53
@stom79 can you also bring the gesture volume/brightness controls in video player. also an option to enable/disable in settings

**Comment by stom79** [comment] 2020-11-29 15:06
I am closing it. Now we will open dedicated issues ;)

**Closed by stom79** 2020-11-29 15:06 UTC
Labels: discussion
